### ISSUE TITLE
[FEATURE] Do not overwrite test data files

### ISSUE THREAD

**Issue by mgovers** [PowerGridModel/power-grid-model-io#198] opened 2023-10-06 08:07 UTC
**Describe the feature request**

Currently, the tests overwrite the test data

This may result in:

* incorrectly passing or failing tests
* progress being lost
* race conditions during testing
* pull requests that accidentally overwrite test data

In particular, when some fixture code (which is executed during pytest-setup) raises an exception, the state might change

Also, not all tests are run: `pytest .` runs all tests but `pytest` only filters for `tests/unit` due to the pyproject configuration.
The filtered-out tests may cause changes tot the test files in `tests/data`

**Proposed solution**

* Do not overwrite any test files. Instead:
* Copy files that are to be updated to temp files
* Only write output to temp directories

TBD: use `pytest` temporary file/directory functionality vs python builtin versions vs `output` directory excluded from check-in via `.gitignore`

**Comment by TonyXiang8787** [comment] 2024-02-19 08:05
@mgovers can you elaborate a bit more detail here? I do not understand the problem. The current validation test only reads the input data right?

**Comment by mgovers** [comment] 2024-02-19 09:06
When running the validation tests, some checked-in files aee also overwritten. I do not know whether those are basically checked-in just like the EXPORT_DATA flag from pgm but they are overwritten anyways

**Comment by mgovers** [comment] 2024-02-19 09:21
basically the stuff in `tests/data/pandapower`. the files were updated even though we only touched the code

**Comment by TonyXiang8787** [comment] 2024-02-19 09:26
I could not reproduce the behavior. If I run `pytest`, no checked-in files in `data` are changed.

**Comment by mgovers** [comment] 2024-02-19 09:38
yes cause the latest versions are checked in. see e.g. https://github.com/PowerGridModel/power-grid-model-io/pull/223/files#diff-30c3ac2f2ff2c6ea16256baa78325c2a2cf73ef5ef407b2b5709e96a7af482bd for a change that did update the data files.

**Comment by mgovers** [comment] 2024-02-19 09:39
you can check the time stamp of the latest `touch` to the file

**Comment by Jerry-Jinfeng-Guo** [comment] 2024-07-08 09:46
Closed in https://github.com/PowerGridModel/power-grid-model-io/pull/262

**Closed by Jerry-Jinfeng-Guo** 2024-07-08 09:46 UTC
Labels: feature, good first issue
